/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static java.lang.Integer.parseInt;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author velet
 */
public class AñadirCancion extends javax.swing.JDialog {

    /**
     * Creates new form AñadirCancion
     */
    private boolean salir;
    public AñadirCancion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        salir = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        duracionCampo = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        rutaCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        añadirBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonBuscarRuta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Vamos a añadir una cancion!");

        duracionCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionCampoActionPerformed(evt);
            }
        });

        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Titulo de la obra");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Duracion de la obra");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Ruta de la obra");

        añadirBoton.setText("Añadir");
        añadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        jLabel5.setText("(en segundos)");

        botonBuscarRuta.setText("jButton1");
        botonBuscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addComponent(salirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(duracionCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(añadirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rutaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonBuscarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(duracionCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(botonBuscarRuta))
                .addGap(18, 18, 18)
                .addComponent(añadirBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(salirBoton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        //Si se le da a salir, este estado pasara a true para evitar conflictos
        salir = true;
        dispose();
    }//GEN-LAST:event_salirBotonActionPerformed

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void duracionCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionCampoActionPerformed

    private void añadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirBotonActionPerformed
        // TODO add your handling code here:
        //Primero comprobar que todos los campos se han rellenado               
        int duracion = -1;
        boolean datosCorrectos = true;
        //Captura la excepcion por si la duracion contiene algun caracter que no sea numerico y lo muestra
        try{
            duracion = parseInt(this.getDuracion());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La duracion debe ser un numero", "ERROR",  JOptionPane.ERROR_MESSAGE);
            datosCorrectos = false;
        }
        //Si lo anterior es correcto comprueba que todo este en orden, la duracion, el titulo y la ruta
        if(datosCorrectos){
            if(this.getTitulo().length() < 3 || duracion < -1 || this.getRuta().isEmpty()){
                //Si algo no cumple los requisitos lo muestra de forma personalizada
                if(this.getTitulo().length() < 3)
                    JOptionPane.showMessageDialog(this, "El titulo debe tener minimo 3 caracteres", "ERROR",  JOptionPane.ERROR_MESSAGE);

                if(duracion < -1)
                    JOptionPane.showMessageDialog(this, "La duracion debe ser positiva", "ERROR",  JOptionPane.ERROR_MESSAGE);

                if(this.getRuta().isEmpty())
                    JOptionPane.showMessageDialog(this, "La ruta debe contener una direccion", "ERROR",  JOptionPane.ERROR_MESSAGE);

            }
            else
                dispose();
        }
    }//GEN-LAST:event_añadirBotonActionPerformed

    private void botonBuscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarRutaActionPerformed
        // TODO add your handling code here:
        JFileChooser selector = new JFileChooser();
        
        int opcion = selector.showOpenDialog(null);
        
        if(opcion == JFileChooser.APPROVE_OPTION)
            this.rutaCampo.setText(selector.getSelectedFile().getPath());
        
    }//GEN-LAST:event_botonBuscarRutaActionPerformed

    public String getTitulo() {
        return campoTitulo.getText();
    }

    public String getDuracion() {
        return duracionCampo.getText();
    }

    public String getRuta() {
        return rutaCampo.getText();
    }
    
    /**
     * Atributo que indicara el estado del boton salir en el JDialog 
     * @return <i> True: Si finalmente se salio del programa </i>
     *         <i> False: Si no se salio del programa </i>
     */
    public boolean getSalir(){
        return salir;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirBoton;
    private javax.swing.JButton botonBuscarRuta;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JTextField duracionCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField rutaCampo;
    private javax.swing.JButton salirBoton;
    // End of variables declaration//GEN-END:variables
}
