/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static java.lang.Integer.parseInt;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author velet
 */
public class ModificarCancion extends javax.swing.JDialog {

    /**
     * Creates new form ModificarCancion
     */
    private boolean salir;
    
    public ModificarCancion(java.awt.Frame parent, boolean modal, String titulo, String duracion, String ruta) {
        super(parent, modal);
        initComponents();
        salir = false;
        inicializarComponentes(titulo, duracion, ruta);
    }

    
    private void inicializarComponentes(String titulo, String duracion, String ruta){
        if(duracion.equals("N/A"))
            duracion = "-1";
        
        this.tituloCampo.setText(titulo);
        this.duracionCampo.setText(duracion);
        this.rutaCampo.setText(ruta);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        duracionCampo = new javax.swing.JTextField();
        botonBuscarRuta = new javax.swing.JButton();
        tituloCampo = new javax.swing.JTextField();
        rutaCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modificarBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Vamos a modificar una cancion!");

        jLabel5.setText("(en segundos)");

        duracionCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionCampoActionPerformed(evt);
            }
        });

        botonBuscarRuta.setText("jButton1");
        botonBuscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarRutaActionPerformed(evt);
            }
        });

        tituloCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloCampoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Titulo de la obra");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Duracion de la obra");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Ruta de la obra");

        modificarBoton.setText("Modificar");
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(duracionCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(modificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rutaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonBuscarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(duracionCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(botonBuscarRuta))
                .addGap(18, 18, 18)
                .addComponent(modificarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(salirBoton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duracionCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionCampoActionPerformed

    private void tituloCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloCampoActionPerformed
    //Metodo que comprueba que lo se que va a modificar sea correcto
    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        // TODO add your handling code here:        
        if(this.getTitulo().length() < 3 || parseInt(this.getDuracion()) < -1 || this.getRuta().isEmpty()){
            if(this.getTitulo().length() < 3)
                JOptionPane.showMessageDialog(this, "El titulo debe tener minimo 3 caracteres", "ERROR",  JOptionPane.ERROR_MESSAGE);
            
            if(parseInt(this.getDuracion()) < -1)
                JOptionPane.showMessageDialog(this, "La duracion debe ser positiva", "ERROR",  JOptionPane.ERROR_MESSAGE);
            
            if(this.getRuta().isEmpty())
                JOptionPane.showMessageDialog(this, "La ruta debe contener una direccion", "ERROR",  JOptionPane.ERROR_MESSAGE);
        }else
            dispose();     
    }//GEN-LAST:event_modificarBotonActionPerformed
    //Booleano que indica si el usuario le dio al boton de salir
    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        // TODO add your handling code here:
        salir = true;
        dispose();
    }//GEN-LAST:event_salirBotonActionPerformed

    private void botonBuscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarRutaActionPerformed
        // TODO add your handling code here:
        
        JFileChooser selector = new JFileChooser();
        
        int opcion = selector.showOpenDialog(null);
        
        if(opcion == JFileChooser.APPROVE_OPTION)
            this.rutaCampo.setText(selector.getSelectedFile().getPath());
    }//GEN-LAST:event_botonBuscarRutaActionPerformed

    public String getTitulo() {
        return tituloCampo.getText();
    }

    public String getDuracion() {
        return duracionCampo.getText();
    }

    public String getRuta() {
        return rutaCampo.getText();
    }
    
    public void setTitulo(String texto){
        tituloCampo.setText(texto);
    }
    
    public boolean getSalir(){
        return salir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarRuta;
    private javax.swing.JTextField duracionCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JTextField rutaCampo;
    private javax.swing.JButton salirBoton;
    private javax.swing.JTextField tituloCampo;
    // End of variables declaration//GEN-END:variables
}
