/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

/**
 *
 * @author juanm
 */
public class opcionGuardado extends javax.swing.JDialog {

    /**
     * Creates new form opcionGuardado
     */
    private String contenido;
    
    public opcionGuardado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        contenido = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGuardadoFormato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        opcionPLS = new javax.swing.JRadioButton();
        opcionM3U = new javax.swing.JRadioButton();
        opcionXSPF = new javax.swing.JRadioButton();
        confirmarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        grupoGuardadoFormato.add(opcionPLS);
        opcionPLS.setText("Guardar en formato PLS");
        opcionPLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPLSActionPerformed(evt);
            }
        });

        grupoGuardadoFormato.add(opcionM3U);
        opcionM3U.setText("Guardar en formato M3U");
        opcionM3U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionM3UActionPerformed(evt);
            }
        });

        grupoGuardadoFormato.add(opcionXSPF);
        opcionXSPF.setText("Guardar en formato XSPF");
        opcionXSPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionXSPFActionPerformed(evt);
            }
        });

        confirmarBoton.setText("Confirmar");
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarBoton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(opcionPLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opcionM3U, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addComponent(opcionXSPF))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(opcionPLS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionM3U)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionXSPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(confirmarBoton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionPLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPLSActionPerformed
        // TODO add your handling code here:
        contenido = "PLS";
    }//GEN-LAST:event_opcionPLSActionPerformed

    private void opcionM3UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionM3UActionPerformed
        // TODO add your handling code here:
        contenido = "M3U";
    }//GEN-LAST:event_opcionM3UActionPerformed

    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_confirmarBotonActionPerformed

    private void opcionXSPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionXSPFActionPerformed
        // TODO add your handling code here:
        contenido = "XSPF";
    }//GEN-LAST:event_opcionXSPFActionPerformed

    public String getContenido(){
        return contenido;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarBoton;
    private javax.swing.ButtonGroup grupoGuardadoFormato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opcionM3U;
    private javax.swing.JRadioButton opcionPLS;
    private javax.swing.JRadioButton opcionXSPF;
    // End of variables declaration//GEN-END:variables
}
